<?php


namespace App\Controllers;


use App\Auth\Auth;
use phpDocumentor\Reflection\Types\Parent_;

class AuthController extends BaseController
{
    public function initController(\CodeIgniter\HTTP\RequestInterface $request, \CodeIgniter\HTTP\ResponseInterface $response, \Psr\Log\LoggerInterface $logger)
    {
        parent::initController($request, $response, $logger); // TODO: Change the autogenerated stub

        // Check Auth
         $this->menu = $this->buildMenu();
    }

    public function _remap($method, ...$params)
    {
        if (!Auth::Check()) {
            return redirect()->route('logout')->send();
        }

        if (method_exists($this, $method)) {
            return $this->$method(...$params);
        }
        throw \CodeIgniter\Exceptions\PageNotFoundException::forPageNotFound();
    }

    /**
     * @var array Navigation & Menu
     */
    protected $menu = [];

    /**
     * @param array $data
     * @return array
     */
    public function preRender(array $data = []): array
    {
        $data = parent::preRender($data);
        $data['user'] = Auth::getUser();
        $data['menu'] = $this->menu;
        return $data;
    }

    public function buildMenu()
    {
        return array(
            "dashboard" => array(
                "title" => "Tableau de Bord",
                "url" => route_to('index'),
                "icon" => "fal fa-home",
                'active' => false
            ),
            "comptes" => array(
                "title" => "Comptes",
                "url" => base_url(),
                "icon" => "fal fa-money-bill",
                'active' => false,
                'sub' => array(
                    'list' => array(
                        "title" => "Liste des Comptes",
                        "url" => route_to('accounts.index'),
                        'active' => false
                    ),
                    'charge' => array(
                        "title" => "Recharger les comptes",
                        "url" => route_to('index'),
                        'active' => false
                    ),
                )
            )
        );
    }

}